### ISSUE TITLE
Further improving package build

### ISSUE THREAD

**Issue by alex-konovalov** [gap-packages/gap-docker-pkg-tests-master-devel#7]
Will be good to reuse parts of `bin/BuildPackages.sh` from GAP to be able to specify additional steps for some packages. For example:
- it can not currently build Semigroups directly from the repository since it needs to download and build libsemigroups first.
- it can not build crisp and irredsol since it needs to run `make` to generate `PackageInfo.g` and do some other things.

**Comment by wilfwilson** [comment]
In order to build the Github version of Semigroups, the following is necessary:

* Clone Semigroups into some folder, say `semigroups`.
* Clone the `stable-0.6` branch of [libsemigroups](https://james-d-mitchell.github.io/libsemigroups/) into `semigroups/src/libsemigroups`, which is available at https://github.com/james-d-mitchell/libsemigroups
* Run `./autogen.sh && ./configure && make` in the `semigroups` directory.

I believe that this is sufficient. Note that Semigroups requires a sufficiently new version of gcc, but I'm not sure what the required version is.

**Comment by alex-konovalov** [comment]
@wilfwilson thanks - this will be very useful when I will be implementing this.

**Comment by alex-konovalov** [comment]
Closed in #6. The solution suggested by @ChrisJefferson and tested by @wilfwilson is to have a standard script `prerequisites.sh` to call it after cloning the repository before building the package. Now suggested it to @bh11 in https://github.com/bh11/crisp/issues/1 for his crisp and irredsol packages.
